using NJsonSchema;
using NJsonSchema.CodeGeneration.CSharp;
using NSwag;
using NSwag.CodeGeneration.CSharp;

// ---------------------------------------------------------------------------
// Contract -> C# model generator (T2). Generates DTOs from the single-source-of-
// truth contracts in integration/contracts into integration/shared/Generated.
// OpenAPI (.yaml)        -> DTOs in namespace PartsPortal.Shared.Contracts.<Name>
// JSON Schema (.schema.json) -> classes in namespace PartsPortal.Shared.Contracts.Messages
// Output files are *.g.cs with <auto-generated> headers (skipped by format/analyzers).
// ---------------------------------------------------------------------------

const string ContractsNs = "PartsPortal.Shared.Contracts";

var repoRoot = FindRepoRoot();
var contractsDir = Path.Combine(repoRoot, "integration", "contracts");
var outDir = Path.Combine(repoRoot, "integration", "shared", "Generated");
Directory.CreateDirectory(outDir);

// Clean previously generated output so deletions in contracts propagate.
foreach (var stale in Directory.EnumerateFiles(outDir, "*.g.cs"))
{
    File.Delete(stale);
}

var written = new List<string>();

// --- OpenAPI documents -> DTOs ---
var openapiDir = Path.Combine(contractsDir, "openapi");
foreach (var path in Directory.EnumerateFiles(openapiDir, "*.yaml").OrderBy(p => p))
{
    var stem = Pascal(Path.GetFileNameWithoutExtension(path));
    var ns = $"{ContractsNs}.{stem}";
    var yaml = await File.ReadAllTextAsync(path);
    var document = await OpenApiYamlDocument.FromYamlAsync(yaml);

    var settings = new CSharpClientGeneratorSettings
    {
        GenerateClientClasses = false,
        GenerateClientInterfaces = false,
        GenerateDtoTypes = true,
    };
    settings.CSharpGeneratorSettings.Namespace = ns;
    settings.CSharpGeneratorSettings.GenerateNullableReferenceTypes = true;
    settings.CSharpGeneratorSettings.JsonLibrary = CSharpJsonLibrary.SystemTextJson;
    settings.CSharpGeneratorSettings.GenerateDataAnnotations = true;

    var code = new CSharpClientGenerator(document, settings).GenerateFile();
    var outPath = Path.Combine(outDir, $"{stem}.g.cs");
    await File.WriteAllTextAsync(outPath, code);
    written.Add(Rel(repoRoot, outPath));
}

// --- JSON Schema message envelopes -> classes ---
// NJsonSchema resolves only the legacy '#/definitions/' ref path, not draft-2020-12
// '#/$defs/'. The contracts stay idiomatic ($defs); we rewrite to 'definitions'
// in-memory before loading so internal refs resolve during generation.
var schemasDir = Path.Combine(contractsDir, "schemas");
foreach (var path in Directory.EnumerateFiles(schemasDir, "*.schema.json").OrderBy(p => p))
{
    var name = Path.GetFileName(path).Replace(".schema.json", string.Empty);
    var stem = Pascal(name);

    // NJsonSchema parses classic JSON Schema best: drop the draft-2020-12 $schema/$id
    // markers and map $defs -> definitions (its resolvable internal-ref location).
    var node = System.Text.Json.Nodes.JsonNode.Parse(await File.ReadAllTextAsync(path))!.AsObject();
    node.Remove("$schema");
    node.Remove("$id");
    var json = node.ToJsonString()
        .Replace("\"$defs\"", "\"definitions\"")
        .Replace("#/$defs/", "#/definitions/");
    var schema = await JsonSchema.FromJsonAsync(json);

    // Generate via NSwag's DTO generator (reliable for object graphs) by registering
    // the root + its definitions as document schemas; internal refs are object-resolved.
    var document = new OpenApiDocument();
    foreach (var def in schema.Definitions)
    {
        document.Definitions[def.Key] = def.Value;
    }
    document.Definitions[schema.Title ?? stem] = schema;

    var settings = new CSharpClientGeneratorSettings
    {
        GenerateClientClasses = false,
        GenerateClientInterfaces = false,
        GenerateDtoTypes = true,
    };
    settings.CSharpGeneratorSettings.Namespace = $"{ContractsNs}.Messages";
    settings.CSharpGeneratorSettings.GenerateNullableReferenceTypes = true;
    settings.CSharpGeneratorSettings.JsonLibrary = CSharpJsonLibrary.SystemTextJson;
    settings.CSharpGeneratorSettings.GenerateDataAnnotations = true;

    var code = new CSharpClientGenerator(document, settings).GenerateFile();
    var outPath = Path.Combine(outDir, $"{stem}.g.cs");
    await File.WriteAllTextAsync(outPath, code);
    written.Add(Rel(repoRoot, outPath));
}

Console.WriteLine($"Generated {written.Count} file(s) into integration/shared/Generated:");
foreach (var f in written)
{
    Console.WriteLine($"  {f}");
}

return 0;

// ---------------------------------------------------------------------------
static string Pascal(string raw)
{
    var parts = raw.Split(['-', '_', '.', ' '], StringSplitOptions.RemoveEmptyEntries);
    return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
}

static string Rel(string root, string path) => Path.GetRelativePath(root, path);

static string FindRepoRoot()
{
    // Walk up from the running assembly until we find the contracts directory.
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        if (Directory.Exists(Path.Combine(dir.FullName, "integration", "contracts")))
        {
            return dir.FullName;
        }
        dir = dir.Parent;
    }
    throw new DirectoryNotFoundException("Could not locate repo root (integration/contracts) above the tool binary.");
}
